"""pae,ao

Revision ID: 018efe33ee0b
Revises: 24de8e4f58c2
Create Date: 2021-10-24 03:13:15.137701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018efe33ee0b'
down_revision = '24de8e4f58c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AO',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applicant.app_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_table('PAE',
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['applicant.app_id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.expert_id'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['project.pro_id'], ),
    sa.PrimaryKeyConstraint('pro_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PAE')
    op.drop_table('AO')
    # ### end Alembic commands ###
