"""添加ao,pe表

Revision ID: 0d34cb19bd17
Revises: 997c594cfb38
Create Date: 2021-10-29 17:10:07.469952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d34cb19bd17'
down_revision = '997c594cfb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AO',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applicant.app_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], )
    )
    op.create_table('PE',
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.expert_id'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['project.pro_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PE')
    op.drop_table('AO')
    # ### end Alembic commands ###
