"""a,e,o,p

Revision ID: 24de8e4f58c2
Revises: ea4df1431692
Create Date: 2021-10-24 03:11:30.020517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24de8e4f58c2'
down_revision = 'ea4df1431692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant',
    sa.Column('app_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('professional', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_t.user_id'], ),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_applicant_app_name'), 'applicant', ['app_name'], unique=False)
    op.create_table('expert',
    sa.Column('expert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expert_name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_t.user_id'], ),
    sa.PrimaryKeyConstraint('expert_id')
    )
    op.create_index(op.f('ix_expert_expert_name'), 'expert', ['expert_name'], unique=False)
    op.create_table('organization',
    sa.Column('org_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_name', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_t.user_id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organization_org_name'), 'organization', ['org_name'], unique=True)
    op.create_table('project',
    sa.Column('pro_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pro_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('app_opinion', sa.String(length=100), nullable=True),
    sa.Column('app_status', sa.String(length=1), nullable=False),
    sa.Column('app_date', sa.DateTime(), nullable=False),
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['pro_class.class_id'], ),
    sa.ForeignKeyConstraint(['info_id'], ['pro_information.info_id'], ),
    sa.PrimaryKeyConstraint('pro_id'),
    sa.UniqueConstraint('pro_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_index(op.f('ix_organization_org_name'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_expert_expert_name'), table_name='expert')
    op.drop_table('expert')
    op.drop_index(op.f('ix_applicant_app_name'), table_name='applicant')
    op.drop_table('applicant')
    # ### end Alembic commands ###
