"""添加pro_info表

Revision ID: 997c594cfb38
Revises: 74e782b9b3aa
Create Date: 2021-10-29 17:07:17.167885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997c594cfb38'
down_revision = '74e782b9b3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pro_information',
    sa.Column('info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('introduction', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pro_id'], ['project.pro_id'], ),
    sa.PrimaryKeyConstraint('info_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pro_information')
    # ### end Alembic commands ###
