"""添加pro表

Revision ID: c80ac25d2364
Revises: 2401771d6b4e
Create Date: 2021-10-26 18:26:50.379599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80ac25d2364'
down_revision = '2401771d6b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('pro_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pro_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('app_opinion', sa.String(length=100), nullable=True),
    sa.Column('app_status', sa.String(length=1), nullable=False),
    sa.Column('app_date', sa.DateTime(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['pro_class.class_id'], ),
    sa.PrimaryKeyConstraint('pro_id'),
    sa.UniqueConstraint('pro_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
