"""u,pi,pc

Revision ID: ea4df1431692
Revises: 
Create Date: 2021-10-24 03:09:16.866344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4df1431692'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pro_class',
    sa.Column('class_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=30), nullable=False),
    sa.Column('pro_class_name', sa.String(length=30), nullable=False),
    sa.Column('over_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('exist_time', sa.DateTime(), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('class_id'),
    sa.UniqueConstraint('pro_class_name')
    )
    op.create_table('pro_information',
    sa.Column('info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('introduction', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('info_id')
    )
    op.create_table('user_t',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_t_username'), 'user_t', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_t_username'), table_name='user_t')
    op.drop_table('user_t')
    op.drop_table('pro_information')
    op.drop_table('pro_class')
    # ### end Alembic commands ###
