"""添加ao,pae表

Revision ID: efb6eda81227
Revises: 72b8699dce7d
Create Date: 2021-10-28 01:50:10.767819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb6eda81227'
down_revision = '72b8699dce7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AO',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applicant.app_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], )
    )
    op.create_table('PAE',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['applicant.app_id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['expert.expert_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PAE')
    op.drop_table('AO')
    # ### end Alembic commands ###
